#!/bin/bash

# Set environment variables for the current shell session
if [[ -z "$LD_LIBRARY_PATH" ]]; then
  export LD_LIBRARY_PATH="/usr/local/lib"
else
  export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib
fi
